dist: trusty
group: travis_latest
language: c
services:
  - docker

env:
  PLATFORM=debian

before_install:
  - docker pull ${PLATFORM}:stable
  - docker run
        --name with-dep
        -v $PWD:/build
        -e PLATFORM=${PLATFORM}
        ${PLATFORM}:stable
        /build/.travis/dep.sh
  - docker commit with-dep ${PLATFORM}:with-dep
script:
  # Build
  - docker run --name with-build
        -v $PWD:/build
        -e PLATFORM=${PLATFORM}
        ${PLATFORM}:with-dep
        /build/.travis/build.sh
  - docker commit with-build ${PLATFORM}:with-build
  # Install
  - docker run --name with-install
        -v $PWD:/build
        -e PLATFORM=${PLATFORM}
        ${PLATFORM}:with-build
        /build/.travis/install.sh
  - docker commit with-install ${PLATFORM}:with-install
  # Verify
  - docker run
    ${PLATFORM}:with-install
    /bin/sh -c "/usr/local/bin/srain --version"

# vim: set tabstop=2:
# vim: set shiftwidth=2:
# vim: set softtabstop=2:
